### ISSUE TITLE
Update to Axum 5 and Clap 4

### ISSUE THREAD

**Issue by kinxiel** [launchbadge/realworld-axum-sqlx#12]
This is a really nice project to learn how to use Axum with Sqlx. Would be nice to have an updated version, because there are some breaking changes which makes navigating the app a bit difficult.

**Comment by davidpdrsn** [comment]
I have made a fork of this repo https://github.com/davidpdrsn/realworld-axum-sqlx with up to date dependencies.

**Comment by kinxiel** [comment]
Thank you for the update. This helps a lot.
